<script setup lang="ts">
import { computed } from 'vue'
import { FileText, MapPinned } from 'lucide-vue-next'
import type { TowerDeviceDetail } from '@/api/towerTypes'
const props=defineProps<{detail?:TowerDeviceDetail;loading?:boolean}>();defineEmits<{archive:[];map:[]}>()
const maintenanceTone=computed(()=>{if(!props.detail)return '';const days=Math.ceil((new Date(props.detail.nextMaintenanceAt).getTime()-new Date('2026-08-11').getTime())/86400000);return days<0?'overdue':days<7?'due':''})
</script>
<template><article class="tech-panel info-card"><div class="panel-head"><h2 class="panel-title">设备详情</h2><span v-if="detail" class="online"><i/>{{ detail.status }}</span></div><div v-if="loading" class="card-state">设备信息加载中...</div><div v-else-if="detail" class="info-body"><div class="identity"><div><small>设备编号</small><b>{{ detail.code }}</b><span>{{ detail.name }}</span></div><strong>{{ detail.model }}</strong></div><dl><div><dt>设备类型</dt><dd>{{ detail.type }}</dd></div><div><dt>最大吊重 / 幅度</dt><dd>{{ detail.maxLoad }} / {{ detail.maxRadius }}</dd></div><div><dt>生产厂家</dt><dd>{{ detail.manufacturer }}</dd></div><div><dt>当前操作员</dt><dd>{{ detail.operator }}</dd></div><div><dt>下次检修</dt><dd :class="maintenanceTone">{{ detail.nextMaintenanceAt }}<em v-if="maintenanceTone==='due'">7天内</em><em v-if="maintenanceTone==='overdue'">已逾期</em></dd></div></dl><div class="card-actions"><button class="tech-button secondary" @click="$emit('map')"><MapPinned :size="13"/>查看地图</button><button class="tech-button" @click="$emit('archive')"><FileText :size="13"/>完整档案</button></div></div><div v-else class="card-state">暂无设备信息</div></article></template>
<style scoped>.info-card{min-height:270px}.online{display:flex;align-items:center;gap:5px;color:#36d399;font-size:9px}.online i{width:6px;height:6px;border-radius:50%;background:#36d399;box-shadow:0 0 7px #36d399}.info-body{padding:10px}.identity{display:flex;align-items:center;justify-content:space-between;padding:9px;border:1px solid rgba(79,168,255,.15);border-radius:5px;background:linear-gradient(90deg,rgba(22,119,255,.12),transparent)}.identity div{display:grid;gap:2px}.identity small{color:#5f819f;font-size:7px}.identity b{color:#dcefff;font-size:13px}.identity span{color:#7795b0;font-size:8px}.identity>strong{color:#54aaff;font-size:9px}dl{margin:5px 0 0}dl div{display:flex;align-items:center;justify-content:space-between;min-height:30px;border-bottom:1px solid rgba(79,168,255,.08)}dt{color:#61809d;font-size:8px}dd{margin:0;color:#a9c0d3;font-size:8px;text-align:right}.due{color:#ffad41}.overdue{color:#ff6478}.due em,.overdue em{margin-left:5px;padding:2px 4px;border-radius:3px;background:rgba(255,154,34,.1);font-style:normal}.card-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.card-state{display:grid;min-height:210px;place-items:center;color:#6d8ca8;font-size:10px}</style>

