<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Camera as CameraIcon, Maximize, Video, VideoOff } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import { getCameraList, getCameraStream } from '@/api/tower'
import type { Camera, CameraStream } from '@/api/towerTypes'
const props=defineProps<{modelValue:boolean;deviceId:string}>();const emit=defineEmits<{ 'update:modelValue':[value:boolean]; manage:[] }>();const visible=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)});const cameras=ref<Camera[]>([]);const activeId=ref('');const stream=ref<CameraStream>();const loading=ref(false);const error=ref('')
const activeCamera=computed(()=>cameras.value.find(c=>c.id===activeId.value));const load=async()=>{loading.value=true;error.value='';try{cameras.value=await getCameraList({deviceId:props.deviceId,pageNum:1,pageSize:100});activeId.value=cameras.value[0]?.id??'';if(activeId.value)stream.value=await getCameraStream(activeId.value)}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
const switchCamera=async(id:string)=>{activeId.value=id;loading.value=true;try{stream.value=await getCameraStream(id)}finally{loading.value=false}}
const screenshot=()=>ElMessage.success('监控截图已保存（模拟）');const fullscreen=()=>{const el=document.querySelector('.video-stage') as HTMLElement|undefined;void el?.requestFullscreen?.()}
watch(()=>[props.modelValue,props.deviceId],()=>{if(props.modelValue)void load()})
</script>
<template><el-dialog v-model="visible" title="实时视频监控" width="min(980px, 94vw)" destroy-on-close><div class="video-toolbar"><div class="camera-tabs"><button v-for="camera in cameras" :key="camera.id" :class="{active:camera.id===activeId}" @click="switchCamera(camera.id)"><i :class="{online:camera.status==='在线'}"/>{{ camera.name }}</button></div><button class="tech-button secondary" @click="emit('manage')">摄像头管理</button></div>
  <div class="video-stage"><div v-if="loading" class="video-state"><span class="loader"/>视频加载中...</div><div v-else-if="error" class="video-state error"><VideoOff/>{{ error }}<button @click="load">重新加载</button></div><div v-else-if="!activeCamera" class="video-state"><VideoOff/>暂无摄像头</div><div v-else-if="stream?.status!=='ready'" class="video-state"><VideoOff/>{{ activeCamera.status==='离线'?'摄像头离线':'暂无信号' }}</div><template v-else><img :src="stream.poster" alt="模拟塔吊实时监控画面"><div class="scanline"/><div class="video-osd"><span><i/> LIVE</span><b>{{ activeCamera.name }} · {{ activeCamera.code }}</b><time>2026-08-11 10:52:36</time></div></template></div>
  <div class="video-footer"><div><Video :size="15"/><span>{{ activeCamera?.name||'未选择摄像头' }}</span><b :class="{online:activeCamera?.status==='在线'}">{{ activeCamera?.status||'—' }}</b></div><button class="tech-button secondary" :disabled="stream?.status!=='ready'" @click="screenshot"><CameraIcon :size="14"/>截图</button><button class="tech-button" :disabled="stream?.status!=='ready'" @click="fullscreen"><Maximize :size="14"/>全屏</button></div>
</el-dialog></template>
<style scoped>
.video-toolbar,.video-footer{display:flex;align-items:center;gap:8px}.camera-tabs{display:flex;flex:1;gap:6px;overflow:auto}.camera-tabs button{display:flex;align-items:center;gap:5px;padding:8px;border:1px solid rgba(79,168,255,.15);border-radius:4px;color:#7796b1;background:rgba(18,52,91,.35);white-space:nowrap;cursor:pointer}.camera-tabs button.active{color:#fff;border-color:#238dff;background:rgba(22,119,255,.22)}.camera-tabs i{width:6px;height:6px;border-radius:50%;background:#73879a}.camera-tabs i.online{background:#36d399;box-shadow:0 0 6px #36d399}.video-stage{position:relative;height:min(58vh,540px);margin:12px 0;overflow:hidden;border:1px solid rgba(67,169,255,.28);border-radius:7px;background:radial-gradient(circle at center,#0d2d4c,#030d18)}.video-stage img{width:100%;height:100%;object-fit:cover;opacity:.68;filter:saturate(.8) contrast(1.1)}.scanline{position:absolute;inset:0;background:repeating-linear-gradient(0deg,rgba(43,180,255,.025) 0 1px,transparent 1px 4px);pointer-events:none}.video-osd{position:absolute;inset:12px 14px auto;display:flex;align-items:center;gap:12px;color:#cde9fb;font-size:10px;text-shadow:0 1px 3px #000}.video-osd span{color:#ff6175}.video-osd span i{display:inline-block;width:6px;height:6px;border-radius:50%;background:#ff6175;box-shadow:0 0 7px #ff6175}.video-osd time{margin-left:auto}.video-state{display:flex;align-items:center;justify-content:center;flex-direction:column;gap:10px;height:100%;color:#6787a3}.video-state.error{color:#ff7585}.loader{width:25px;height:25px;border:2px solid rgba(73,175,255,.2);border-top-color:#36bcff;border-radius:50%;animation:spin .8s linear infinite}.video-footer>div{display:flex;align-items:center;gap:7px;flex:1;color:#7998b4}.video-footer b{color:#899daf}.video-footer b.online{color:#36d399}@keyframes spin{to{transform:rotate(360deg)}}
</style>
