<script setup lang="ts">
import { onMounted,ref } from 'vue';import { ElMessage,ElMessageBox,type FormInstance,type FormRules } from 'element-plus';import { Edit3,Eye,Plus,Trash2 } from 'lucide-vue-next';import ResourceState from '@/components/common/ResourceState.vue';import { createFoundationPit,deleteFoundationPit,getFoundationPitDetail,getFoundationPitPage,updateFoundationPit,type FoundationPitPayload,type FoundationPitRecord } from '@/api/foundationPit';import { getProjectList,type ProjectRecord } from '@/api/project'
const rows=ref<FoundationPitRecord[]>([]),projects=ref<ProjectRecord[]>([]),loading=ref(false),error=ref(''),page=ref(1),size=ref(10),total=ref(0),dialog=ref(false),detailDialog=ref(false),detail=ref<FoundationPitRecord>(),saving=ref(false),formRef=ref<FormInstance>();
const blank=():FoundationPitPayload=>({pitCode:'',pitName:'',projectId:0,progress:0,monitoringStatus:0});const form=ref<FoundationPitPayload>(blank());const rules:FormRules={pitCode:[{required:true,message:'请输入基坑编号'}],pitName:[{required:true,message:'请输入基坑名称'}],projectId:[{required:true,message:'请选择所属项目'}]};
const load=async()=>{loading.value=true;error.value='';try{const [r,p]=await Promise.all([getFoundationPitPage(page.value,size.value),getProjectList()]);rows.value=r.data.records;total.value=r.data.total;projects.value=p.data}catch(e){error.value=e instanceof Error?e.message:'网络异常'}finally{loading.value=false}};
const edit=async(row?:FoundationPitRecord)=>{form.value=row?{...(await getFoundationPitDetail(row.id)).data}:blank();dialog.value=true};const view=async(row:FoundationPitRecord)=>{detail.value=(await getFoundationPitDetail(row.id)).data;detailDialog.value=true};
const save=async()=>{if(!await formRef.value?.validate())return;saving.value=true;try{form.value.id?await updateFoundationPit(form.value):await createFoundationPit(form.value);dialog.value=false;ElMessage.success('基坑保存成功');await load()}finally{saving.value=false}};const remove=async(row:FoundationPitRecord)=>{await ElMessageBox.confirm(`确认删除基坑“${row.pitName}”？`,'删除确认',{type:'warning'});await deleteFoundationPit(row.id);ElMessage.success('基坑已删除');await load()};onMounted(load)
</script>
<template><article class="tech-panel"><div class="panel-head"><h2 class="panel-title">基坑档案与监测</h2><button class="tech-button" @click="edit()"><Plus :size="14"/>新增基坑</button></div><ResourceState :loading="loading" :error="error" :empty="!rows.length" @retry="load"><el-table :data="rows"><el-table-column prop="pitCode" label="基坑编号"/><el-table-column prop="pitName" label="基坑名称"/><el-table-column prop="pitType" label="类型"/><el-table-column prop="currentStage" label="当前阶段"/><el-table-column prop="progress" label="进度(%)"/><el-table-column prop="riskLevel" label="风险等级"/><el-table-column label="监测状态"><template #default="{row}">{{ ['正常','预警','报警','停止施工'][row.monitoringStatus]??'未知' }}</template></el-table-column><el-table-column label="操作" width="190"><template #default="{row}"><el-button link @click="view(row)"><Eye :size="13"/>详情</el-button><el-button link @click="edit(row)"><Edit3 :size="13"/>修改</el-button><el-button link type="danger" @click="remove(row)"><Trash2 :size="13"/>删除</el-button></template></el-table-column></el-table><div class="resource-pagination"><span>共 {{ total }} 个基坑</span><el-pagination v-model:current-page="page" v-model:page-size="size" layout="prev,pager,next,sizes" :total="total" @change="load"/></div></ResourceState></article>
<el-dialog v-model="dialog" :title="form.id?'修改基坑':'新增基坑'" width="min(860px,94vw)"><el-form ref="formRef" :model="form" :rules="rules" label-width="110px" class="pit-form"><el-form-item label="基坑编号" prop="pitCode"><el-input v-model="form.pitCode"/></el-form-item><el-form-item label="基坑名称" prop="pitName"><el-input v-model="form.pitName"/></el-form-item><el-form-item label="所属项目" prop="projectId"><el-select v-model="form.projectId"><el-option v-for="p in projects" :key="p.id" :label="p.projectName" :value="p.id"/></el-select></el-form-item><el-form-item label="基坑类型"><el-input v-model="form.pitType"/></el-form-item><el-form-item label="开挖方式"><el-input v-model="form.excavationMethod"/></el-form-item><el-form-item label="面积"><el-input-number v-model="form.area" :min="0"/></el-form-item><el-form-item label="支护形式"><el-input v-model="form.supportType"/></el-form-item><el-form-item label="当前阶段"><el-select v-model="form.currentStage"><el-option v-for="x in ['未开挖','土方开挖','支护施工','降水施工','基础施工','已回填']" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="施工进度"><el-input-number v-model="form.progress" :min="0" :max="100"/></el-form-item><el-form-item label="风险等级"><el-select v-model="form.riskLevel"><el-option v-for="x in ['低','中','高','重大']" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="监测状态"><el-select v-model="form.monitoringStatus"><el-option label="正常" :value="0"/><el-option label="预警" :value="1"/><el-option label="报警" :value="2"/><el-option label="停止施工" :value="3"/></el-select></el-form-item><el-form-item label="负责人"><el-input v-model="form.responsiblePerson"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.responsiblePhone"/></el-form-item><el-form-item label="位置"><el-input v-model="form.locationAddress"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></el-form><template #footer><button class="tech-button secondary" @click="dialog=false">取消</button><button class="tech-button" :disabled="saving" @click="save">保存</button></template></el-dialog>
<el-dialog v-model="detailDialog" title="基坑详情"><div v-if="detail" class="detail-grid"><div v-for="(value,key) in detail" :key="key"><small>{{ key }}</small><b>{{ value??'—' }}</b></div></div></el-dialog></template>
<style scoped>.resource-pagination{display:flex;justify-content:space-between;padding:10px;color:#6f8da9}.pit-form{display:grid;grid-template-columns:1fr 1fr}.detail-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.detail-grid>div{padding:9px;border:1px solid rgba(79,168,255,.13)}.detail-grid small,.detail-grid b{display:block}@media(max-width:700px){.pit-form,.detail-grid{grid-template-columns:1fr}}</style>
