<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { ElMessage,ElMessageBox,type FormInstance,type FormRules } from 'element-plus';import { Edit3,Eye,MapPinned,Plus,Trash2,Video } from 'lucide-vue-next';import ResourceState from '@/components/common/ResourceState.vue';import ProjectMap from '@/components/project/ProjectMap.vue';import CameraVideoDialog from './CameraVideoDialog.vue';import { createCamera,deleteCamera,getCameraDetail,getCameraPage,updateCamera,type CameraDetail,type CameraPayload,type CameraRecord } from '@/api/camera';import { getProjectList,type ProjectRecord } from '@/api/project'
const data=ref<CameraRecord[]>([]),projects=ref<ProjectRecord[]>([]),loading=ref(false),error=ref(''),total=ref(0),page=ref(1),size=ref(10),keyword=ref(''),status=ref<number|''>(''),detail=ref<CameraDetail>(),detailDialog=ref(false),videoDialog=ref(false),mapDialog=ref(false),dialog=ref(false),saving=ref(false),selected=ref<CameraRecord>(),formRef=ref<FormInstance>();
const blank=():CameraPayload=>({cameraCode:'',cameraName:'',projectId:0,status:1,hasAudio:0,hasPtz:0});const form=ref<CameraPayload>(blank());const rules:FormRules={cameraCode:[{required:true,message:'请输入摄像头编号'}],cameraName:[{required:true,message:'请输入摄像头名称'}],projectId:[{required:true,message:'请选择所属项目'}]};
const rows=computed(()=>data.value.filter(x=>(!keyword.value||`${x.cameraName}${x.cameraCode}`.includes(keyword.value))&&(status.value===''||x.status===status.value)));
const load=async()=>{loading.value=true;error.value='';try{const [r,p]=await Promise.all([getCameraPage(page.value,size.value),getProjectList()]);data.value=r.data.records;total.value=r.data.total;projects.value=p.data}catch(e){error.value=e instanceof Error?e.message:'网络异常'}finally{loading.value=false}};
const view=async(row:CameraRecord)=>{loading.value=true;try{detail.value=(await getCameraDetail(row.id)).data;detailDialog.value=true}finally{loading.value=false}};
const edit=async(row?:CameraRecord)=>{if(!row){form.value=blank();dialog.value=true;return}const d=(await getCameraDetail(row.id)).data;form.value={...d,id:row.id,projectId:d.projectId??0};dialog.value=true};
const save=async()=>{if(!await formRef.value?.validate())return;saving.value=true;try{form.value.id?await updateCamera(form.value):await createCamera(form.value);dialog.value=false;ElMessage.success('摄像头保存成功');await load()}finally{saving.value=false}};
const remove=async(row:CameraRecord)=>{await ElMessageBox.confirm(`确认删除摄像头“${row.cameraName}”？`,'删除确认',{type:'warning'});await deleteCamera(row.id);ElMessage.success('摄像头已删除');await load()};onMounted(load)
</script>
<template><article class="tech-panel"><div class="panel-head"><h2 class="panel-title">摄像头管理</h2><button class="tech-button" @click="edit()"><Plus :size="14"/>新增摄像头</button></div><div class="resource-toolbar"><el-input v-model="keyword" clearable placeholder="摄像头名称 / 编号"/><el-select v-model="status" clearable placeholder="在线状态"><el-option label="在线" :value="1"/><el-option label="离线" :value="0"/></el-select><button class="tech-button secondary" @click="load">查询</button></div><ResourceState :loading="loading" :error="error" :empty="!rows.length" @retry="load"><el-table :data="rows"><el-table-column prop="cameraCode" label="摄像头编号"/><el-table-column prop="cameraName" label="摄像头名称"/><el-table-column prop="cameraType" label="类型"/><el-table-column prop="manufacturer" label="厂家"/><el-table-column prop="installationAddress" label="安装位置"/><el-table-column label="状态"><template #default="{row}"><span class="status-pill" :class="row.status===1?'status-running':'status-offline'">{{ row.status===1?'在线':'离线' }}</span></template></el-table-column><el-table-column label="操作" width="290" fixed="right"><template #default="{row}"><el-button link @click="view(row)"><Eye :size="13"/>详情</el-button><el-button link @click="edit(row)"><Edit3 :size="13"/>修改</el-button><el-button link @click="selected=row;videoDialog=true"><Video :size="13"/>视频</el-button><el-button link @click="selected=row;mapDialog=true"><MapPinned :size="13"/>定位</el-button><el-button link type="danger" @click="remove(row)"><Trash2 :size="13"/>删除</el-button></template></el-table-column></el-table><div class="resource-pagination"><span>共 {{ total }} 个摄像头</span><el-pagination v-model:current-page="page" v-model:page-size="size" layout="prev,pager,next,sizes" :total="total" @change="load"/></div></ResourceState></article>
<el-dialog v-model="dialog" :title="form.id?'修改摄像头':'新增摄像头'" width="min(760px,92vw)"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="摄像头编号" prop="cameraCode"><el-input v-model="form.cameraCode"/></el-form-item><el-form-item label="摄像头名称" prop="cameraName"><el-input v-model="form.cameraName"/></el-form-item><el-form-item label="所属项目" prop="projectId"><el-select v-model="form.projectId"><el-option v-for="p in projects" :key="p.id" :label="p.projectName" :value="p.id"/></el-select></el-form-item><el-form-item label="类型"><el-input v-model="form.cameraType"/></el-form-item><el-form-item label="厂商"><el-input v-model="form.manufacturer"/></el-form-item><el-form-item label="设备型号"><el-input v-model="form.deviceModel"/></el-form-item><el-form-item label="安装地址"><el-input v-model="form.installationAddress"/></el-form-item><el-form-item label="监控方向"><el-input v-model="form.direction"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="离线" :value="0"/><el-option label="在线" :value="1"/><el-option label="故障" :value="2"/><el-option label="停用" :value="3"/></el-select></el-form-item><el-form-item label="能力"><el-checkbox v-model="form.hasAudio" :true-value="1" :false-value="0">音频</el-checkbox><el-checkbox v-model="form.hasPtz" :true-value="1" :false-value="0">云台</el-checkbox></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea"/></el-form-item></el-form><template #footer><button class="tech-button secondary" @click="dialog=false">取消</button><button class="tech-button" :disabled="saving" @click="save">保存</button></template></el-dialog>
<el-dialog v-model="detailDialog" title="摄像头详情"><div v-if="detail" class="detail-grid"><div v-for="(value,key) in detail" :key="key"><small>{{ key }}</small><b>{{ value??'—' }}</b></div></div></el-dialog><CameraVideoDialog v-model="videoDialog" :camera="selected"/><el-dialog v-model="mapDialog" title="摄像头地图定位"><ProjectMap :name="selected?.cameraName"/></el-dialog></template>
<style scoped>.resource-toolbar{display:grid;grid-template-columns:1.5fr 1fr auto;gap:8px;padding:12px}.resource-pagination{display:flex;justify-content:space-between;padding:10px;color:#6f8da9}.detail-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.detail-grid>div{padding:9px;border:1px solid rgba(79,168,255,.13)}.detail-grid small,.detail-grid b{display:block}@media(max-width:650px){.resource-toolbar,.detail-grid{grid-template-columns:1fr}}</style>
