<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Eye } from 'lucide-vue-next'
import { getCameraList } from '@/api/tower'
import type { Camera } from '@/api/towerTypes'
const props=defineProps<{modelValue:boolean}>();const emit=defineEmits<{ 'update:modelValue':[value:boolean]; view:[camera:Camera] }>();const visible=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)});const data=ref<Camera[]>([]);const loading=ref(false);const error=ref('');const pageNum=ref(1);const pageSize=ref(20);const load=async()=>{loading.value=true;error.value='';try{data.value=await getCameraList({pageNum:pageNum.value,pageSize:pageSize.value})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}};watch(()=>props.modelValue,v=>{if(v)void load()})
</script>
<template><el-dialog v-model="visible" title="摄像头管理" width="min(1050px, 94vw)"><div v-if="loading" class="table-state">摄像头列表加载中...</div><div v-else-if="error" class="table-state error">{{ error }}</div><div v-else-if="!data.length" class="table-state">暂无摄像头</div><div v-else class="camera-table"><div class="row head"><span>编号</span><span>名称</span><span>所属项目</span><span>所属设备</span><span>安装位置</span><span>在线状态</span><span>最后在线</span><span>操作</span></div><div v-for="item in data" :key="item.id" class="row"><span>{{ item.code }}</span><span>{{ item.name }}</span><span>{{ item.project }}</span><span>{{ item.target }}</span><span>{{ item.position }}</span><span :class="{online:item.status==='在线'}">{{ item.status }}</span><span>{{ item.lastOnlineAt }}</span><button class="tech-button secondary" @click="emit('view',item)"><Eye :size="12"/>查看视频</button></div></div></el-dialog></template>
<style scoped>.camera-table{overflow:auto}.row{display:grid;grid-template-columns:.8fr 1.2fr 1.1fr 1fr 1fr .7fr 1.1fr .8fr;align-items:center;min-width:850px;padding:9px;border-bottom:1px solid rgba(79,168,255,.1);color:#9cb5ca;font-size:10px}.row.head{color:#55a6df;background:rgba(22,119,255,.08)}.row .online{color:#36d399}.row button{padding:5px 6px}.table-state{display:grid;min-height:300px;place-items:center;color:#718fab}.table-state.error{color:#ff7283}</style>
