<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import MaintenanceRecord from './MaintenanceRecord.vue'
import { getMaintenanceRecords, getTowerDeviceDetail } from '@/api/tower'
import type { MaintenanceRecord as RecordType, TowerDeviceDetail } from '@/api/towerTypes'
const props=defineProps<{modelValue:boolean;deviceId:string}>();const emit=defineEmits<{ 'update:modelValue':[value:boolean] }>();const visible=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)});const detail=ref<TowerDeviceDetail>();const records=ref<RecordType[]>([]);const loading=ref(false);const error=ref('');const load=async()=>{loading.value=true;error.value='';try{[detail.value,records.value]=await Promise.all([getTowerDeviceDetail(props.deviceId),getMaintenanceRecords(props.deviceId)])}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}};watch(()=>[props.modelValue,props.deviceId],()=>{if(props.modelValue)void load()})
</script>
<template><el-dialog v-model="visible" title="设备完整档案" width="min(980px, 94vw)" top="5vh"><div v-if="error" class="archive-state error">{{ error }}<button @click="load">重新加载</button></div><template v-else-if="detail"><div class="archive-grid"><div v-for="(value,key) in detail" :key="key"><span>{{ ({code:'设备编号',name:'设备名称',model:'设备型号',type:'设备类型',maxLoad:'最大吊重',maxRadius:'最大工作幅度',maxHeight:'最大起升高度',manufacturer:'生产厂家',installedAt:'安装日期',lastMaintenanceAt:'最近检修日期',nextMaintenanceAt:'下次检修日期',operator:'当前操作员',project:'所属施工项目',status:'设备状态'} as Record<string,string>)[key]||key }}</span><b>{{ value }}</b></div></div><h3>维护管理记录</h3><MaintenanceRecord :records="records" :loading="loading"/></template><div v-else class="archive-state">{{ loading?'设备档案加载中...':'暂无设备档案' }}</div></el-dialog></template>
<style scoped>.archive-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.archive-grid>div{padding:9px;border:1px solid rgba(79,168,255,.13);border-radius:4px;background:rgba(9,31,56,.52)}.archive-grid span{display:block;color:#6786a1;font-size:9px}.archive-grid b{display:block;margin-top:4px;color:#d4e7f6;font-size:10px}.archive-grid>div:first-child{display:none}h3{margin:16px 0 9px;color:#ddecf8;font-size:13px}.archive-state{display:grid;min-height:360px;place-items:center;color:#6f8fab}.archive-state.error{color:#ff7182}@media(max-width:700px){.archive-grid{grid-template-columns:repeat(2,1fr)}}</style>

