<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Download } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import LineChart from '@/charts/LineChart.vue'
import BarChart from '@/charts/BarChart.vue'
import { exportTowerHistoryData, getTowerHistoryData } from '@/api/tower'
import type { HistoryData, TowerDevice } from '@/api/towerTypes'
const props=defineProps<{modelValue:boolean;deviceId:string;devices:TowerDevice[]}>();const emit=defineEmits<{ 'update:modelValue':[value:boolean]; 'update:deviceId':[value:string] }>()
const visible=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)});const range=ref('today');const tab=ref('weight');const loading=ref(false);const exporting=ref(false);const error=ref('');const data=ref<HistoryData>();const start=ref('');const end=ref('')
const ranges=[['1h','最近1小时'],['today','今天'],['7d','最近7天'],['30d','最近30天'],['custom','自定义时间']];const tabs=[['weight','吊重曲线'],['torque','力矩曲线'],['wind','风速曲线'],['rotation','回转角度'],['alarms','报警记录'],['online','设备在线率']]
const chart= computed(()=>{if(!data.value)return {name:'',values:[],unit:''};const map={weight:['吊重',data.value.weight,'T'],torque:['力矩',data.value.torque,'m·T'],wind:['风速',data.value.wind,'m/s'],rotation:['回转角度',data.value.rotation,'°'],online:['在线率',data.value.onlineRate,'%']} as Record<string,[string,number[],string]>;const item=map[tab.value]??map.weight;return {name:item[0],values:item[1],unit:item[2]}})
const load=async()=>{loading.value=true;error.value='';try{data.value=await getTowerHistoryData({deviceId:props.deviceId,range:range.value,start:start.value,end:end.value})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
const exportData=async()=>{exporting.value=true;try{const blob=await exportTowerHistoryData({deviceId:props.deviceId,range:range.value});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`塔吊历史数据-${props.deviceId}.csv`;link.click();URL.revokeObjectURL(url);ElMessage.success('CSV 已导出')}finally{exporting.value=false}}
watch(()=>[props.modelValue,props.deviceId,range.value],()=>{if(props.modelValue)void load()})
</script>
<template><el-dialog v-model="visible" title="历史数据分析" width="min(1120px, 95vw)" top="5vh" destroy-on-close><div class="history-toolbar"><select :value="deviceId" @change="$emit('update:deviceId',($event.target as HTMLSelectElement).value)"><option v-for="d in devices" :key="d.id" :value="d.id">{{ d.name }}</option></select><div class="ranges"><button v-for="r in ranges" :key="r[0]" :class="{active:range===r[0]}" @click="range=r[0]">{{ r[1] }}</button></div><div v-if="range==='custom'" class="custom-range"><input v-model="start" type="datetime-local"><span>至</span><input v-model="end" type="datetime-local"><button @click="load">查询</button></div><button class="tech-button export" :disabled="loading||exporting" @click="exportData"><Download :size="14" />{{ exporting?'导出中...':'导出数据' }}</button></div>
  <div class="tabbar"><button v-for="t in tabs" :key="t[0]" :class="{active:tab===t[0]}" @click="tab=t[0]">{{ t[1] }}</button></div>
  <div v-if="loading" class="dialog-state">历史数据加载中...</div><div v-else-if="error" class="dialog-state error">{{ error }}<button @click="load">重新加载</button></div><template v-else-if="data"><div class="history-summary"><div v-for="(value,key) in data.summary" :key="key"><small>{{ ({maxLoad:'最大吊重',maxWind:'最大风速',avgTorque:'平均力矩',onlineRate:'设备在线率'} as Record<string,string>)[key] }}</small><b>{{ value }}</b></div></div><div v-if="tab==='alarms'" class="history-table"><div class="row head"><span>时间</span><span>类型</span><span>等级</span><span>状态</span></div><div v-for="alarm in data.alarms" :key="alarm.id" class="row"><span>{{ alarm.time }}</span><span>{{ alarm.type }}</span><span>{{ alarm.level }}</span><span>{{ alarm.status }}</span></div></div><div v-else class="history-chart"><BarChart v-if="tab==='online'" :labels="data.labels" :values="chart.values"/><LineChart v-else :labels="data.labels" :series="[{name:chart.name,data:chart.values,color:'#35b8ff',area:true}]" :unit="chart.unit"/></div></template><div v-else class="dialog-state">暂无历史数据</div>
</el-dialog></template>
<style scoped>
.history-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.history-toolbar select,.custom-range input{height:32px;padding:0 8px;border:1px solid rgba(79,168,255,.2);border-radius:4px;color:#b8d1e5;background:#091d34}.ranges,.tabbar{display:flex;gap:5px}.ranges button,.tabbar button,.custom-range button{padding:7px 10px;border:1px solid rgba(79,168,255,.14);border-radius:4px;color:#7796b3;background:rgba(18,52,91,.36);cursor:pointer}.ranges button:hover,.ranges button.active,.tabbar button:hover,.tabbar button.active{color:#fff;border-color:#258cff;background:rgba(22,119,255,.25)}.custom-range{display:flex;align-items:center;gap:5px;color:#6786a2}.export{margin-left:auto}.tabbar{margin:14px 0 10px;overflow:auto}.tabbar button{white-space:nowrap}.history-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.history-summary>div{padding:10px;border:1px solid rgba(79,168,255,.14);border-radius:5px;background:rgba(9,34,61,.55)}.history-summary small{color:#6f8da8;font-size:9px}.history-summary b{display:block;margin-top:4px;color:#d7eafa;font-size:18px}.history-chart{height:350px;margin-top:10px}.history-table{max-height:350px;margin-top:10px;overflow:auto}.row{display:grid;grid-template-columns:1.4fr 1fr .6fr .7fr;padding:10px;border-bottom:1px solid rgba(79,168,255,.1);color:#9ab4ca;font-size:10px}.row.head{color:#5fa9df;background:rgba(22,119,255,.08)}.dialog-state{display:grid;min-height:380px;place-items:center;color:#718fab}.dialog-state.error{color:#ff7283}@media(max-width:720px){.history-summary{grid-template-columns:repeat(2,1fr)}.export{margin-left:0}.history-chart{height:300px}}
</style>

