<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { ShieldCheck } from 'lucide-vue-next'
import { getOperationLogs } from '@/api/tower'
import type { OperationLog } from '@/api/towerTypes'
const props=defineProps<{modelValue:boolean}>();const emit=defineEmits<{ 'update:modelValue':[value:boolean] }>();const visible=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)});const data=ref<OperationLog[]>([]);const loading=ref(false);const error=ref('');const filter=ref('全部');const permissionOpen=ref(false);const types=['全部','报警确认','报警关闭','修改设备信息','修改报警阈值','查看历史数据','导出报表','查看视频'];const filtered=computed(()=>filter.value==='全部'?data.value:data.value.filter(x=>x.type===filter.value));const load=async()=>{loading.value=true;error.value='';try{data.value=await getOperationLogs({})}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}};watch(()=>props.modelValue,v=>{if(v)void load()})
</script>
<template><el-dialog v-model="visible" title="操作日志" width="min(1080px, 95vw)"><div class="log-toolbar"><div class="log-filter"><button v-for="t in types" :key="t" :class="{active:filter===t}" @click="filter=t">{{ t }}</button></div><button class="tech-button secondary" @click="permissionOpen=!permissionOpen"><ShieldCheck :size="13"/>权限入口</button></div><div v-if="permissionOpen" class="permission-preview"><div><strong>监管中心管理员</strong><span>报警处置 · 设备档案 · 阈值配置 · 报表导出</span></div><div><strong>项目安全员</strong><span>报警确认 · 视频查看 · 历史数据</span></div><div><strong>只读访客</strong><span>实时数据 · 设备地图</span></div><small>当前为权限入口预览，后续接入统一身份与角色权限接口。</small></div><div v-if="loading" class="log-state">日志加载中...</div><div v-else-if="error" class="log-state error">{{ error }}</div><div v-else-if="!filtered.length" class="log-state">暂无操作日志</div><div v-else class="log-table"><div class="row head"><span>操作人</span><span>操作时间</span><span>操作类型</span><span>操作对象</span><span>操作内容</span><span>IP 地址</span><span>结果</span></div><div v-for="item in filtered" :key="item.id" class="row"><span>{{ item.operator }}</span><span>{{ item.time }}</span><span>{{ item.type }}</span><span>{{ item.target }}</span><span>{{ item.content }}</span><span>{{ item.ip }}</span><span class="success">{{ item.result }}</span></div></div></el-dialog></template>
<style scoped>.log-toolbar{display:flex;align-items:flex-start;gap:8px;margin-bottom:10px}.log-filter{display:flex;flex:1;gap:5px;overflow:auto}.log-filter button{padding:7px 9px;border:1px solid rgba(79,168,255,.14);border-radius:4px;color:#7895af;background:rgba(18,52,91,.35);white-space:nowrap;cursor:pointer}.log-filter button.active,.log-filter button:hover{color:#fff;border-color:#258cff;background:rgba(22,119,255,.24)}.permission-preview{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:10px;padding:9px;border:1px solid rgba(79,168,255,.17);border-radius:5px;background:rgba(8,31,56,.65)}.permission-preview>div{display:grid;gap:4px;padding:8px;border:1px solid rgba(79,168,255,.1);border-radius:4px}.permission-preview strong{color:#d3e7f6;font-size:10px}.permission-preview span{color:#718faa;font-size:8px}.permission-preview small{grid-column:1/-1;color:#537692;font-size:8px}.log-table{overflow:auto}.row{display:grid;grid-template-columns:.7fr 1.2fr .8fr .8fr 1.6fr .8fr .5fr;min-width:860px;padding:10px;border-bottom:1px solid rgba(79,168,255,.1);color:#9db5c9;font-size:10px}.row.head{color:#58a8df;background:rgba(22,119,255,.08)}.success{color:#36d399}.log-state{display:grid;min-height:300px;place-items:center;color:#6d8ca8}.log-state.error{color:#ff7182}@media(max-width:700px){.permission-preview{grid-template-columns:1fr}}</style>
