<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Building2, Camera, Construction, MapPin, ShieldAlert } from 'lucide-vue-next'
import { getProjectMapData } from '@/api/tower'
import type { MapPoint } from '@/api/towerTypes'
const props=defineProps<{modelValue:boolean;projectId:string}>();const emit=defineEmits<{ 'update:modelValue':[value:boolean] }>();const visible=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)});const points=ref<MapPoint[]>([]);const selected=ref<MapPoint>();const loading=ref(false);const error=ref('');const iconMap={project:Building2,tower:Construction,camera:Camera,pit:MapPin,alarm:ShieldAlert};const load=async()=>{loading.value=true;error.value='';try{points.value=await getProjectMapData(props.projectId)}catch(e){error.value=e instanceof Error?e.message:'地图加载失败'}finally{loading.value=false}};watch(()=>props.modelValue,v=>{if(v)void load()})
</script>
<template><el-dialog v-model="visible" title="项目设备地图" width="min(1000px, 94vw)"><div class="map-note">模拟点位 · 已预留 <code>getProjectMapData(projectId)</code> 与地图适配层，后续可接入高德地图或百度地图</div><div class="map-stage"><div v-if="loading" class="map-state">地图数据加载中...</div><div v-else-if="error" class="map-state error">{{ error }}<button @click="load">重新加载</button></div><template v-else><button v-for="point in points" :key="point.id" class="map-marker" :class="point.type" :style="{left:point.x+'%',top:point.y+'%'}" @click="selected=point"><component :is="iconMap[point.type]" :size="17"/><span>{{ point.name }}</span></button><div v-if="selected" class="map-popup"><button @click="selected=undefined">×</button><strong>{{ selected.name }}</strong><span>编号：{{ selected.code }}</span><span>状态：<b>{{ selected.status }}</b></span></div></template></div><div class="legend"><span v-for="(label,key) in {project:'施工项目',tower:'塔吊',camera:'摄像头',pit:'基坑',alarm:'报警设备'}" :key="key"><i :class="key"/>{{ label }}</span></div></el-dialog></template>
<style scoped>.map-note{margin-bottom:8px;color:#6d8ca8;font-size:9px}.map-note code{color:#4fb9f6}.map-stage{position:relative;height:min(58vh,520px);overflow:hidden;border:1px solid rgba(79,168,255,.22);border-radius:6px;background:radial-gradient(circle at 50% 50%,rgba(20,79,121,.3),transparent 48%),linear-gradient(rgba(48,127,184,.09) 1px,transparent 1px),linear-gradient(90deg,rgba(48,127,184,.09) 1px,transparent 1px),#07192b;background-size:auto,34px 34px,34px 34px,auto}.map-stage:after{position:absolute;inset:13% 8%;border:7px double rgba(56,136,192,.16);border-radius:45% 12% 36% 18%;content:'';transform:rotate(-8deg)}.map-marker{position:absolute;z-index:2;display:flex;align-items:center;gap:4px;padding:6px;border:1px solid rgba(70,174,255,.4);border-radius:5px;color:#65beff;background:#0b3153;box-shadow:0 0 12px rgba(32,146,235,.25);cursor:pointer;transform:translate(-50%,-50%)}.map-marker span{font-size:8px;white-space:nowrap}.map-marker.camera{color:#49e5ca}.map-marker.pit{color:#fbbf24}.map-marker.alarm{color:#ff6075;border-color:#ff6075;animation:map-alarm 1.8s infinite}.map-popup{position:absolute;z-index:4;top:15px;right:15px;display:grid;gap:6px;min-width:190px;padding:12px;border:1px solid rgba(72,178,255,.35);border-radius:6px;color:#91aec5;background:rgba(5,24,43,.94);font-size:10px}.map-popup button{position:absolute;top:4px;right:6px;border:0;color:#8dadc8;background:none}.map-popup strong{color:#dcefff}.map-popup b{color:#39d9a3}.legend{display:flex;gap:14px;margin-top:8px;color:#718eaa;font-size:9px}.legend span{display:flex;align-items:center;gap:4px}.legend i{width:7px;height:7px;border-radius:50%;background:#4babf6}.legend i.camera{background:#49e5ca}.legend i.pit{background:#fbbf24}.legend i.alarm{background:#ff6075}.map-state{position:absolute;z-index:3;inset:0;display:grid;place-items:center;color:#6d8ca8;background:#07192b}.map-state.error{color:#ff7182}@keyframes map-alarm{50%{box-shadow:0 0 22px rgba(255,70,95,.55)}}</style>

